name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: self-hosted

    defaults:
      run:
        working-directory: parent_module

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "341b1f51-173e-43f9-a204-d6846c6a92bd" \
            --password "9fP8Q~EfSajcXzS6fmjLLWr7nnIyHAMOsxSW.a.2" \
            --tenant "8dd47890-014e-4d4a-9706-c08392fd00d0"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "d4fb712a-aae3-49cf-8c1b-9ed8f8b11a56"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: self-hosted

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: parent_module

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "341b1f51-173e-43f9-a204-d6846c6a92bd" \
            --password "9fP8Q~EfSajcXzS6fmjLLWr7nnIyHAMOsxSW.a.2" \
            --tenant "8dd47890-014e-4d4a-9706-c08392fd00d0"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "d4fb712a-aae3-49cf-8c1b-9ed8f8b11a56"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan